definitions:
  transport.CheckCodeRequest:
    description: Request structure for checking a code
    properties:
      code:
        type: string
      username:
        type: string
    type: object
  transport.CheckCodeResponse:
    description: Response structure for checking a code
    properties:
      valid:
        type: boolean
    type: object
  transport.CheckUsernameResponse:
    description: Check if a username exists
    properties:
      found:
        type: boolean
    type: object
  transport.CreateTagRequest:
    properties:
      tag:
        $ref: '#/definitions/types.Tag'
    type: object
  transport.CreateTagResponse:
    properties:
      tag:
        $ref: '#/definitions/types.Tag'
    type: object
  transport.GetNoteResponse:
    properties:
      category_id:
        type: integer
      category_owner:
        type: integer
      checked:
        type: boolean
      content: {}
      copied_at:
        type: integer
      cover:
        type: string
      created_at:
        type: integer
      creator:
        type: integer
      font:
        type: string
      id:
        type: string
      original: {}
      source:
        type: string
      tags:
        items:
          $ref: '#/definitions/types.Tag'
        type: array
      title:
        type: string
      type:
        type: integer
    type: object
  transport.LogInResponse:
    properties:
      authorization:
        type: string
      refresh:
        type: string
      user:
        $ref: '#/definitions/types.User'
    type: object
  transport.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  transport.NewNoteRequest:
    properties:
      category_id:
        type: integer
      category_owner:
        type: integer
      checked:
        type: boolean
      content: {}
      copied_at:
        type: integer
      cover:
        type: string
      created_at:
        type: integer
      font:
        type: string
      original: {}
      source:
        type: string
      tags:
        items:
          $ref: '#/definitions/types.Tag'
        type: array
      title:
        type: string
      type:
        type: integer
    type: object
  transport.NewNoteResponse:
    properties:
      note_id:
        type: string
    type: object
  transport.SignUpRequest:
    properties:
      code:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  transport.UpdateNoteRequest:
    additionalProperties: true
    type: object
  types.Tag:
    properties:
      color:
        type: string
      id:
        type: integer
      owner:
        type: integer
      text:
        type: string
    type: object
  types.User:
    properties:
      avatar:
        type: string
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      tg_username:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/notes:
    post:
      consumes:
      - application/json
      description: Create a new note
      parameters:
      - description: Access JWT
        in: header
        name: Authorization
        required: true
        type: string
      - description: New Note Request
        in: body
        name: NewNoteRequest
        required: true
        schema:
          $ref: '#/definitions/transport.NewNoteRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/transport.NewNoteResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create Note
      tags:
      - notes
  /api/notes/{note_id}:
    get:
      consumes:
      - application/json
      description: Retrieve a specific note by its ID
      parameters:
      - description: Access JWT
        in: header
        name: Authorization
        required: true
        type: string
      - description: Note ID
        in: path
        name: note_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.GetNoteResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get Note
      tags:
      - notes
    patch:
      consumes:
      - application/json
      description: Update a specific note by its ID
      parameters:
      - description: Access JWT
        in: header
        name: Authorization
        required: true
        type: string
      - description: Note ID
        in: path
        name: note_id
        required: true
        type: string
      - description: Update Note Request
        in: body
        name: UpdateNoteRequest
        required: true
        schema:
          $ref: '#/definitions/transport.UpdateNoteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update Note
      tags:
      - notes
  /api/tags:
    post:
      consumes:
      - application/json
      description: Create a new tag
      parameters:
      - description: Access JWT
        in: header
        name: Authorization
        required: true
        type: string
      - description: Create Tag Request
        in: body
        name: CreateTagRequest
        required: true
        schema:
          $ref: '#/definitions/transport.CreateTagRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.CreateTagResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create Tag
      tags:
      - tags
  /api/users/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves a user by their ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.User'
      summary: Get a user by ID
      tags:
      - users
  /api/users/check-code:
    post:
      consumes:
      - application/json
      description: Check if the provided code is valid for the given username
      parameters:
      - description: Request body for checking code
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/transport.CheckCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.CheckCodeResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Check if a code is valid
      tags:
      - users
  /api/users/check-username:
    get:
      description: Check if a username exists in the database
      parameters:
      - description: Username to check
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.CheckUsernameResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Check if a username exists
      tags:
      - users
  /api/users/login:
    post:
      consumes:
      - application/json
      description: Logs in a user and returns the user ID, refresh token, and access
        token.
      parameters:
      - description: User details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/transport.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.LogInResponse'
      summary: Log in a user
      tags:
      - users
  /api/users/refresh_token:
    get:
      consumes:
      - application/json
      description: Refreshes the access token using the refresh token.
      parameters:
      - description: Refresh token
        in: query
        name: refresh
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.LogInResponse'
      summary: Refresh access token
      tags:
      - users
  /api/users/signup:
    post:
      consumes:
      - application/json
      description: Registers a new user and returns the user ID, refresh token, and
        access token.
      parameters:
      - description: User details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/transport.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.LogInResponse'
      summary: Sign up a new user
      tags:
      - users
swagger: "2.0"
