definitions:
  transport.CheckCodeRequest:
    properties:
      code:
        type: string
      username:
        type: string
    type: object
  transport.CheckCodeResponse:
    properties:
      valid:
        type: boolean
    type: object
  transport.CheckUsernameResponse:
    properties:
      found:
        type: boolean
    type: object
  transport.CreateTagRequest:
    properties:
      tag:
        $ref: '#/definitions/types.Tag'
    type: object
  transport.CreateTagResponse:
    properties:
      tag:
        $ref: '#/definitions/types.Tag'
    type: object
  transport.GetNoteResponse:
    properties:
      category_id:
        type: integer
      category_owner:
        type: integer
      checked:
        type: boolean
      content: {}
      copied_at:
        type: integer
      cover:
        type: string
      created_at:
        type: integer
      creator:
        type: integer
      font:
        type: string
      id:
        type: string
      original: {}
      source:
        type: string
      tags:
        items:
          $ref: '#/definitions/types.Tag'
        type: array
      title:
        type: string
      type:
        type: integer
    type: object
  transport.LogInResponse:
    properties:
      authorization:
        type: string
      user:
        $ref: '#/definitions/types.User'
    type: object
  transport.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  transport.NewNoteRequest:
    properties:
      category_id:
        type: integer
      category_owner:
        type: integer
      checked:
        type: boolean
      content: {}
      copied_at:
        type: integer
      cover:
        type: string
      created_at:
        type: integer
      font:
        type: string
      original: {}
      source:
        type: string
      tags:
        items:
          $ref: '#/definitions/types.Tag'
        type: array
      title:
        type: string
      type:
        type: integer
    type: object
  transport.NewNoteResponse:
    properties:
      note_id:
        type: string
    type: object
  transport.RefreshAccessTokenResponse:
    properties:
      authorization:
        type: string
    type: object
  transport.SignUpRequest:
    properties:
      code:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  transport.SignUpResponse:
    properties:
      authorization:
        type: string
      user:
        $ref: '#/definitions/types.User'
    type: object
  transport.UpdateNoteRequest:
    additionalProperties: true
    type: object
  types.Tag:
    properties:
      color:
        type: string
      id:
        type: integer
      owner:
        type: integer
      text:
        type: string
    type: object
  types.User:
    properties:
      avatar:
        type: string
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      tg_username:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/notes:
    post:
      consumes:
      - application/json
      description: Create a new note
      parameters:
      - description: Access JWT
        in: header
        name: Authorization
        required: true
        type: string
      - description: New Note Request
        in: body
        name: NewNoteRequest
        required: true
        schema:
          $ref: '#/definitions/transport.NewNoteRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/transport.NewNoteResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create Note
      tags:
      - notes
  /api/notes/{note_id}:
    get:
      consumes:
      - application/json
      description: Retrieve a specific note by its ID
      parameters:
      - description: Access JWT
        in: header
        name: Authorization
        required: true
        type: string
      - description: Note ID
        in: path
        name: note_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.GetNoteResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get Note
      tags:
      - notes
    patch:
      consumes:
      - application/json
      description: Update a specific note by its ID
      parameters:
      - description: Access JWT
        in: header
        name: Authorization
        required: true
        type: string
      - description: Note ID
        in: path
        name: note_id
        required: true
        type: string
      - description: Update Note Request
        in: body
        name: UpdateNoteRequest
        required: true
        schema:
          $ref: '#/definitions/transport.UpdateNoteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update Note
      tags:
      - notes
  /api/tags:
    post:
      consumes:
      - application/json
      description: Create a new tag
      parameters:
      - description: Access JWT
        in: header
        name: Authorization
        required: true
        type: string
      - description: Create Tag Request
        in: body
        name: CreateTagRequest
        required: true
        schema:
          $ref: '#/definitions/transport.CreateTagRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.CreateTagResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create Tag
      tags:
      - tags
  /api/users/{id}:
    get:
      description: Get user information by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.User'
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get user information
      tags:
      - users
  /api/users/check-code:
    post:
      consumes:
      - application/json
      description: Check if a verification code is valid for the given username
      parameters:
      - description: Check code request
        in: body
        name: checkCodeRequest
        required: true
        schema:
          $ref: '#/definitions/transport.CheckCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.CheckCodeResponse'
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Check verification code
      tags:
      - users
  /api/users/check-username:
    get:
      description: Check if a username is available
      parameters:
      - description: Username to check
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.CheckUsernameResponse'
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Check username availability
      tags:
      - users
  /api/users/login:
    post:
      consumes:
      - application/json
      description: Log in a user with username and password
      parameters:
      - description: Login request
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/transport.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.LogInResponse'
        "400":
          description: Bad request
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Log in a user
      tags:
      - users
  /api/users/refresh:
    get:
      consumes:
      - application/json
      description: Refresh the access token using the refresh token in cookies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.RefreshAccessTokenResponse'
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Refresh access token
      tags:
      - users
  /api/users/signup:
    post:
      consumes:
      - application/json
      description: Sign up a new user with username, password, and verification code
      parameters:
      - description: Sign up request
        in: body
        name: signupRequest
        required: true
        schema:
          $ref: '#/definitions/transport.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.SignUpResponse'
        "400":
          description: Bad request
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Sign up a new user
      tags:
      - users
  /api/users/update:
    put:
      consumes:
      - multipart/form-data
      description: Update user's avatar and username
      parameters:
      - description: User's avatar
        in: formData
        name: avatar
        type: file
      - description: User's username
        in: formData
        name: username
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update user information
      tags:
      - users
swagger: "2.0"
