version: '3.8'

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - .env:/app/.env
    ports:
      - 3001:3001
    restart: always
    command: make run
    depends_on:
      - db
  
  authbot:
    build: 
      context: ./authbot
      dockerfile: Dockerfile
    volumes:
      - ./authbot:/app
      - .env:/app/.env
    command: make run
    restart: always
    depends_on:
      - db
      - redis

  app:
    image: node:latest
    command: npm run dev
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      - HOST=0.0.0.0
    ports:
      - 3000:3000
    restart: always

  db:
    image: postgres
    environment:
      POSTGRES_DB: keep_it
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
      - api
      - db
    restart: always
    
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: always
  
  redis:
    image: redis:4.0.5-alpine
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 6379:6379