version: '3.8'

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - .env/:/app/.env
      - ./files:/app/files
    ports:
      - 3001:3001
    command: make run
    depends_on:
      - db
      - redis
      - kafka

  authbot:
    build: 
      context: ./authbot
      dockerfile: Dockerfile
    volumes:
      - ./authbot:/app
      - .env:/app/.env
    command: make run
    depends_on:
      - db
      - redis

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_SEGMENT_BYTES: 16777216
      KAFKA_LOG_RETENTION_BYTES: 134217728
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./configs/kafka/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf


  parser-tg:
    build: 
      context: ./parsers/telegram
      dockerfile: Dockerfile
    volumes:
      - ./parsers/telegram:/app
      - .env:/app/.env
      - ./files:/app/files
    command: make run
    depends_on:
      - kafka
      - api

  parser-vk:
    build: 
      context: ./parsers/vk
      dockerfile: Dockerfile
    volumes:
      - ./parsers/vk:/app
      - .env:/app/.env
      - ./files:/app/files
    command: make run
    depends_on:
      - kafka
      - api
  
  app:
    image: node:latest
    command: npm run dev 
    volumes:
      - ./app:/app
      - .env:/app/.env
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./configs/nginx/nginx-local.conf:/etc/nginx/nginx.conf
      - ./files:/usr/share/nginx/files
      - ./static:/usr/share/nginx/static
    depends_on:
      - api
      - app

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]